server:
  port: ${port:8080}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
loggin:
  level:
    com:
      board: DEBUG
spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
  profiles:
    include: secret
    active: ${profile}